package com.talenteck.ttanalytics;

import java.util.Arrays;
import java.util.Hashtable;

public class LiveReportTableQuery {
	public String fetchCuttoffQuery(String startDate,String endDate,String location,String country,String sample,String rate){
		
		/*if(!location.equalsIgnoreCase("All") && country.equalsIgnoreCase("All")){
			String[] USLocations = {"Dallas","Phoenix","Charlotte","Miramar","Houston","Charleston","Fort Lauderdale","Columbus"};
			String[] PhilippinesLocations = {"Dasmarinas","Clark1","Davao","Clark2","Clark3"};
			
		if(Arrays.asList(USLocations).contains(location))
			country = "US";		
		else if(Arrays.asList(PhilippinesLocations).contains(location))
			country = "Philippines";
		else country = "Rest";
		
		}*/
		
		rate = "`" + rate + "`" ;
		String query = "SELECT percentile," + rate + " AS rate FROM applicantreportcutoff WHERE LOWER(country)=LOWER('" + country + "') AND LOWER(location)=LOWER('"+ location + "') AND percentile IN (10,30,50,70,90,100) ORDER BY percentile ASC";
		//System.out.println(query);

		return query;		
	}
		
	//Given the Selectors run the query to get the table data
	//Date startDate,Date endDate,String location,String sample,String rate	
	
	public String fetchQuery(String startDate,String endDate,String location,String country,String sample,String rate,Hashtable<Integer, Double> cutoffs) {
			String query ="";
			String locationCondition = "";
			String countryCondition="";
			String sampleCondition = "";
			String predictable ="";
			
		if(!location.equalsIgnoreCase("All")){
			locationCondition =" AND LOWER(applicantlocx) = LOWER('" + location + "')";
		}
		if(country.equalsIgnoreCase("Rest")){
			countryCondition =" AND applicantcountry IN ('Panama City','Mexico','India','Hong Kong','Canada') ";
		}
		if(!country.equalsIgnoreCase("All") && !country.equalsIgnoreCase("Rest")){
			countryCondition =" AND LOWER(applicantcountry) = LOWER('" + country + "')";
		}

		if(!sample.equalsIgnoreCase("All"))	{
			sampleCondition=" AND LOWER(modeltype) = LOWER('" + sample + "')";
		}	
		
		switch(rate){
		case "30-Day":
			predictable="p30";
			break;
		case "60-Day":
			predictable="p60";
			break;
		case "90-Day":
			predictable="p90";
			break;
		case "180-Day":
			predictable="p180";
			break;
		case "365-Day":
			predictable="p365";
			break;
			
		}
		rate = "`" + rate + "`" ;
		
		
		/*query = "SELECT CASE WHEN quantileNumber IS NOT NULL THEN quantileNumber ELSE 'Total Scored' END AS quantileNumber,COALESCE(SUM(applicants),0) AS applicants,COALESCE(SUM(papplicants),0) AS papplicants,COALESCE(SUM(interviewed),0) AS interviewed,COALESCE(SUM(pinterviewed),0) AS pinterviewed,COALESCE(SUM(offered),0) AS offered,COALESCE(SUM(poffered),0) AS poffered,COALESCE(SUM(accepted),0) AS accepted,COALESCE(SUM(paccepted),0) AS paccepted,COALESCE(SUM(hired),0) AS hired,COALESCE(SUM(phired),0) AS phired,COALESCE(SUM(terminatedd),0) AS terminatedd,COALESCE(SUM(pterminatedd),0) AS pterminatedd,COALESCE(SUM(xdayeligibility),0) AS xdayeligibility,COALESCE(SUM(pxdayeligibility),0) AS pxdayeligibility,COALESCE(SUM(xdayturnover),0) AS xdayturnover FROM("
				+       "SELECT 1 AS quantileNumber,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS applicants,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0)  AS papplicants,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS interviewed,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS pinterviewed,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS offered ,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS poffered,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS accepted ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS paccepted ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS hired ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS phired ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, 1, 0)),0) AS terminatedd ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, "+ predictable +", 0)),0) AS pterminatedd , COUNT("+rate+") AS xdayeligibility,COALESCE(SUM(IF(" +rate+ " IS NOT NULL,"+ predictable +",0)),0) AS pxdayeligibility,ROUND((COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, 1, 0))/COUNT("+rate+"),0))*100,1) AS xdayturnover FROM applicantreport WHERE "+ predictable +"<="+ cutoffs.get(1) +" AND receiveddate BETWEEN '"+ startDate+"' AND '"+ endDate +"'" + locationCondition + countryCondition + sampleCondition
				+ "UNION SELECT 2 AS quantileNumber,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS applicants,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0)  AS papplicants,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS interviewed,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS pinterviewed,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS offered ,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS poffered,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS accepted ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS paccepted ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS hired ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS phired ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, 1, 0)),0) AS terminatedd ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, "+ predictable +", 0)),0) AS pterminatedd , COUNT("+rate+") AS xdayeligibility,COALESCE(SUM(IF(" +rate+ " IS NOT NULL,"+ predictable +",0)),0) AS pxdayeligibility,ROUND((COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, 1, 0))/COUNT("+rate+"),0))*100,1) AS xdayturnover FROM applicantreport WHERE "+ predictable +">"+ cutoffs.get(1) +" AND "+ predictable +"<="+ cutoffs.get(2) +" AND receiveddate BETWEEN '"+ startDate+"' AND '"+ endDate +"'" + locationCondition + countryCondition +sampleCondition
				+ "UNION SELECT 3 AS quantileNumber,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS applicants,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0)  AS papplicants,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS interviewed,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS pinterviewed,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS offered ,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS poffered,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS accepted ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS paccepted ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS hired ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS phired ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, 1, 0)),0) AS terminatedd ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, "+ predictable +", 0)),0) AS pterminatedd , COUNT("+rate+") AS xdayeligibility,COALESCE(SUM(IF(" +rate+ " IS NOT NULL,"+ predictable +",0)),0) AS pxdayeligibility,ROUND((COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, 1, 0))/COUNT("+rate+"),0))*100,1) AS xdayturnover FROM applicantreport WHERE "+ predictable +">"+ cutoffs.get(2) +" AND "+ predictable +"<="+ cutoffs.get(3) +" AND receiveddate BETWEEN '"+ startDate+"' AND '"+ endDate +"'" + locationCondition + countryCondition +sampleCondition
				+ "UNION SELECT 4 AS quantileNumber,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS applicants,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0)  AS papplicants,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS interviewed,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS pinterviewed,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS offered ,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS poffered,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS accepted ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS paccepted ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS hired ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS phired ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, 1, 0)),0) AS terminatedd ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, "+ predictable +", 0)),0) AS pterminatedd , COUNT("+rate+") AS xdayeligibility,COALESCE(SUM(IF(" +rate+ " IS NOT NULL,"+ predictable +",0)),0) AS pxdayeligibility,ROUND((COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, 1, 0))/COUNT("+rate+"),0))*100,1) AS xdayturnover FROM applicantreport WHERE "+ predictable +">"+ cutoffs.get(3) +" AND "+ predictable +"<="+ cutoffs.get(4) +" AND receiveddate BETWEEN '"+ startDate+"' AND '"+ endDate +"'" + locationCondition + countryCondition +sampleCondition
				+ "UNION SELECT 5 AS quantileNumber,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS applicants,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0)  AS papplicants,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS interviewed,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS pinterviewed,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS offered ,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS poffered,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS accepted ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS paccepted ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS hired ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS phired ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, 1, 0)),0) AS terminatedd ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, "+ predictable +", 0)),0) AS pterminatedd , COUNT("+rate+") AS xdayeligibility,COALESCE(SUM(IF(" +rate+ " IS NOT NULL,"+ predictable +",0)),0) AS pxdayeligibility,ROUND((COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, 1, 0))/COUNT("+rate+"),0))*100,1) AS xdayturnover FROM applicantreport WHERE "+ predictable +">"+ cutoffs.get(4) +" AND "+ predictable +"<="+ cutoffs.get(5) +" AND receiveddate BETWEEN '"+ startDate+"' AND '"+ endDate +"'" + locationCondition + countryCondition +sampleCondition
				+ "UNION SELECT 6 AS quantileNumber,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS applicants,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0)  AS papplicants,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS interviewed,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS pinterviewed,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS offered ,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS poffered,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS accepted ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS paccepted ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS hired ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS phired ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, 1, 0)),0) AS terminatedd ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, "+ predictable +", 0)),0) AS pterminatedd , COUNT("+rate+") AS xdayeligibility,COALESCE(SUM(IF(" +rate+ " IS NOT NULL,"+ predictable +",0)),0) AS pxdayeligibility,ROUND((COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, 1, 0))/COUNT("+rate+"),0))*100,1) AS xdayturnover FROM applicantreport WHERE "+ predictable +">"+ cutoffs.get(5) +" AND receiveddate BETWEEN '"+ startDate+"' AND '"+ endDate +"'" + locationCondition + countryCondition + sampleCondition +")AS c GROUP BY quantileNumber WITH ROLLUP "
				+ "UNION SELECT 'Non-Scored' AS quantileNumber,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NULL, 1, 0)),0) AS applicants,null,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NULL, 1, 0)),0) AS interviewed,null,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NULL, 1, 0)),0) AS offered ,null,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NULL, 1, 0)),0) AS accepted ,null,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NULL, 1, 0)),0) AS hired ,null,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NULL AND "+rate+"=1, 1, 0)),0) AS terminatedd ,null,COALESCE(SUM(IF("+ predictable +" IS NULL AND "+rate+" IS NOT NULL, 1, 0)),0) AS xdayeligibility,null,ROUND((COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NULL AND "+rate+"=1, 1, 0))/COUNT("+rate+"),0))*100,1) AS xdayturnover FROM applicantreport WHERE receiveddate BETWEEN '"+ startDate+"' AND '"+ endDate +"' " + locationCondition + countryCondition ;*/
		 
		
		query = "SELECT CASE WHEN quantileNumber IS NOT NULL THEN quantileNumber ELSE 'Total Scored' END AS quantileNumber,COALESCE(SUM(applicants),0) AS applicants,COALESCE(SUM(papplicants),0) AS papplicants,COALESCE(SUM(interviewed),0) AS interviewed,COALESCE(SUM(pinterviewed),0) AS pinterviewed,COALESCE(SUM(offered),0) AS offered,COALESCE(SUM(poffered),0) AS poffered,COALESCE(SUM(accepted),0) AS accepted,COALESCE(SUM(paccepted),0) AS paccepted,COALESCE(SUM(hired),0) AS hired,COALESCE(SUM(phired),0) AS phired,COALESCE(SUM(terminatedd),0) AS terminatedd,COALESCE(SUM(pterminatedd),0) AS pterminatedd,COALESCE(SUM(xdayeligibility),0) AS xdayeligibility,COALESCE(SUM(pxdayeligibility),0) AS pxdayeligibility,COALESCE(SUM(xdayturnover),0) AS xdayturnover FROM("
				+       "SELECT 1 AS quantileNumber,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS applicants,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0)  AS papplicants,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS interviewed,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS pinterviewed,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS offered ,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS poffered,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS accepted ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS paccepted ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS hired ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS phired ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, 1, 0)),0) AS terminatedd ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, "+ predictable +", 0)),0) AS pterminatedd , COALESCE(SUM(if(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+rate+" IS NOT NULL,1,0)),0) AS xdayeligibility,COALESCE(SUM(IF(" +rate+ " IS NOT NULL,"+ predictable +",0)),0) AS pxdayeligibility,ROUND((COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, 1, 0))/COUNT("+rate+"),0))*100,1) AS xdayturnover FROM applicantreport WHERE "+ predictable +"<="+ cutoffs.get(1) +" AND receiveddate BETWEEN '"+ startDate+"' AND '"+ endDate +"'" + locationCondition + countryCondition + sampleCondition
				+ "UNION SELECT 2 AS quantileNumber,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS applicants,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0)  AS papplicants,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS interviewed,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS pinterviewed,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS offered ,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS poffered,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS accepted ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS paccepted ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS hired ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS phired ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, 1, 0)),0) AS terminatedd ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, "+ predictable +", 0)),0) AS pterminatedd , COALESCE(SUM(if(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+rate+" IS NOT NULL,1,0)),0) AS xdayeligibility,COALESCE(SUM(IF(" +rate+ " IS NOT NULL,"+ predictable +",0)),0) AS pxdayeligibility,ROUND((COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, 1, 0))/COUNT("+rate+"),0))*100,1) AS xdayturnover FROM applicantreport WHERE "+ predictable +">"+ cutoffs.get(1) +" AND "+ predictable +"<="+ cutoffs.get(2) +" AND receiveddate BETWEEN '"+ startDate+"' AND '"+ endDate +"'" + locationCondition + countryCondition +sampleCondition
				+ "UNION SELECT 3 AS quantileNumber,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS applicants,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0)  AS papplicants,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS interviewed,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS pinterviewed,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS offered ,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS poffered,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS accepted ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS paccepted ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS hired ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS phired ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, 1, 0)),0) AS terminatedd ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, "+ predictable +", 0)),0) AS pterminatedd , COALESCE(SUM(if(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+rate+" IS NOT NULL,1,0)),0) AS xdayeligibility,COALESCE(SUM(IF(" +rate+ " IS NOT NULL,"+ predictable +",0)),0) AS pxdayeligibility,ROUND((COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, 1, 0))/COUNT("+rate+"),0))*100,1) AS xdayturnover FROM applicantreport WHERE "+ predictable +">"+ cutoffs.get(2) +" AND "+ predictable +"<="+ cutoffs.get(3) +" AND receiveddate BETWEEN '"+ startDate+"' AND '"+ endDate +"'" + locationCondition + countryCondition +sampleCondition
				+ "UNION SELECT 4 AS quantileNumber,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS applicants,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0)  AS papplicants,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS interviewed,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS pinterviewed,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS offered ,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS poffered,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS accepted ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS paccepted ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS hired ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS phired ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, 1, 0)),0) AS terminatedd ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, "+ predictable +", 0)),0) AS pterminatedd , COALESCE(SUM(if(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+rate+" IS NOT NULL,1,0)),0) AS xdayeligibility,COALESCE(SUM(IF(" +rate+ " IS NOT NULL,"+ predictable +",0)),0) AS pxdayeligibility,ROUND((COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, 1, 0))/COUNT("+rate+"),0))*100,1) AS xdayturnover FROM applicantreport WHERE "+ predictable +">"+ cutoffs.get(3) +" AND "+ predictable +"<="+ cutoffs.get(4) +" AND receiveddate BETWEEN '"+ startDate+"' AND '"+ endDate +"'" + locationCondition + countryCondition +sampleCondition
				+ "UNION SELECT 5 AS quantileNumber,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS applicants,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0)  AS papplicants,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS interviewed,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS pinterviewed,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS offered ,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS poffered,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS accepted ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS paccepted ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS hired ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS phired ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, 1, 0)),0) AS terminatedd ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, "+ predictable +", 0)),0) AS pterminatedd , COALESCE(SUM(if(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+rate+" IS NOT NULL,1,0)),0) AS xdayeligibility,COALESCE(SUM(IF(" +rate+ " IS NOT NULL,"+ predictable +",0)),0) AS pxdayeligibility,ROUND((COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, 1, 0))/COUNT("+rate+"),0))*100,1) AS xdayturnover FROM applicantreport WHERE "+ predictable +">"+ cutoffs.get(4) +" AND "+ predictable +"<="+ cutoffs.get(5) +" AND receiveddate BETWEEN '"+ startDate+"' AND '"+ endDate +"'" + locationCondition + countryCondition +sampleCondition
				+ "UNION SELECT 6 AS quantileNumber,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS applicants,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0)  AS papplicants,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS interviewed,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS pinterviewed,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS offered ,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS poffered,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS accepted ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS paccepted ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NOT NULL, 1, 0)),0) AS hired ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NOT NULL, "+ predictable +", 0)),0) AS phired ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, 1, 0)),0) AS terminatedd ,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, "+ predictable +", 0)),0) AS pterminatedd , COALESCE(SUM(if(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+rate+" IS NOT NULL,1,0)),0) AS xdayeligibility,COALESCE(SUM(IF(" +rate+ " IS NOT NULL,"+ predictable +",0)),0) AS pxdayeligibility,ROUND((COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NOT NULL AND "+rate+"=1, 1, 0))/COUNT("+rate+"),0))*100,1) AS xdayturnover FROM applicantreport WHERE "+ predictable +">"+ cutoffs.get(5) +" AND receiveddate BETWEEN '"+ startDate+"' AND '"+ endDate +"'" + locationCondition + countryCondition + sampleCondition +")AS c GROUP BY quantileNumber WITH ROLLUP "
				+ "UNION SELECT 'Non-Scored' AS quantileNumber,COALESCE(SUM(IF(applicantid IS NOT NULL AND "+ predictable +" IS NULL, 1, 0)),0) AS applicants,null,COALESCE(SUM(IF(firstinterviewdate IS NOT NULL AND "+ predictable +" IS NULL, 1, 0)),0) AS interviewed,null,COALESCE(SUM(IF(offerdate IS NOT NULL AND "+ predictable +" IS NULL, 1, 0)),0) AS offered ,null,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL  AND acceptdate !='0000-00-00' AND "+ predictable +" IS NULL, 1, 0)),0) AS accepted ,null,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND hiredate IS NOT NULL AND "+ predictable +" IS NULL, 1, 0)),0) AS hired ,null,COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NULL AND "+rate+"=1, 1, 0)),0) AS terminatedd ,null,COALESCE(SUM(IF("+ predictable +" IS NULL AND "+rate+" IS NOT NULL, 1, 0)),0) AS xdayeligibility,null,ROUND((COALESCE(SUM(IF(offerdate IS NOT NULL AND acceptdate IS NOT NULL AND acceptdate !='0000-00-00' AND "+ predictable +" IS NULL AND "+rate+"=1, 1, 0))/COUNT("+rate+"),0))*100,1) AS xdayturnover FROM applicantreport WHERE receiveddate BETWEEN '"+ startDate+"' AND '"+ endDate +"' " + locationCondition + countryCondition ;

		 
		
		//System.out.println(query);
		return query;		
	}

}
